In [7]:
from pathlib import Path
import pandas as pd
from matriculas.data import load_raw_data

RAW_DIR = Path("../data/raw")

dataset_path = (
    RAW_DIR
    / "reporte1_31_08_26"
    / "reporte1_31_08_26.xlsx"
)

df = load_raw_data(dataset_path)

df.head()

   period course_code  enrollment
0  201510   2024-0001         143
1  201510   2024-0003          28
2  201510   2024-0005          27
3  201510   2024-0006          46
4  201510   2024-0007          45

In [8]:
#Vamos a verificar los tipos de datos que se tienen y la cantidad de no nulos que hay
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47383 entries, 0 to 47382
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   period       47383 non-null  int64
 1   course_code  47383 non-null  str
 2   enrollment   47383 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.1 MB

In [9]:
#En principio que soberva que el período es un int, pero no tiene sentido. Hay que convertirlo a 
#semestre y año. Para eso vamos a crear una nueva columna que se llame "periodo" y que contenga el año y el semestre.
df['period'].unique()
#Se puede ver que hay valores 21, 41, 50, etc en los semestres que por ahora eliminaré. Solo me 
#quedaré con valores 10 y 20. Para eso voy a crear una nueva columna que se llame "periodo" y que contenga el año y el semestre.

array([201510, 201511, 201520, 201521, 201541, 201542, 201550, 201610,
       201611, 201620, 201621, 201641, 201642, 201650, 201710, 201711,
       201712, 201720, 201721, 201724, 201741, 201750, 201810, 201811,
       201812, 201820, 201821, 201841, 201850, 201910, 201911, 201920,
       201921, 201922, 201924, 201941, 201950, 202010, 202011, 202014,
       202020, 202021, 202024, 202041, 202050, 202110, 202111, 202114,
       202120, 202121, 202124, 202150, 202210, 202211, 202214, 202220,
       202221, 202224, 202241, 202250, 202310, 202311, 202314, 202320,
       202321, 202324, 202341, 202350, 202410, 202411, 202414, 202420,
       202421, 202424, 202441, 202450, 202510, 202511, 202514, 202520,
       202521, 202524, 202541, 202550, 202610, 202611, 202614, 202620,
       202650, 202710])

In [10]:
from matriculas.prepare import prepare_period

df_periods = prepare_period(df, column="period")

df_periods[
    ["period", "year", "semester", "time_index"]
].drop_duplicates().sort_values("time_index")

       period  year  semester  time_index
0      201510  2015         1           0
1684   201520  2015         2           1
3447   201610  2016         1           2
5241   201620  2016         2           3
7119   201710  2017         1           4
8993   201720  2017         2           5
11020  201810  2018         1           6
12973  201820  2018         2           7
15177  201910  2019         1           8
17262  201920  2019         2           9
19541  202010  2020         1          10
21713  202020  2020         2          11
23950  202110  2021         1          12
26042  202120  2021         2          13
28174  202210  2022         1          14
30169  202220  2022         2          15
32343  202310  2023         1          16
34355  202320  2023         2          17
36390  202410  2024         1          18
38355  202420  2024         2          19
40268  202510  2025         1          20
42131  202520  2025         2          21
43960  202610  2026         1          22
45754  202620  2026         2          23
47382  202710  2027         1          24

In [12]:
df_periods

       period course_code  enrollment  year  semester  time_index
0      201510   2024-0001         143  2015         1           0
1      201510   2024-0003          28  2015         1           0
2      201510   2024-0005          27  2015         1           0
3      201510   2024-0006          46  2015         1           0
4      201510   2024-0007          45  2015         1           0
...       ...         ...         ...   ...       ...         ...
47350  202620   SOCL-0006          68  2026         2          23
47351  202620   SOGS-0003           5  2026         2          23
47352  202620   UPBM-0001         542  2026         2          23
47353  202620   UPBM-0003        1209  2026         2          23
47382  202710   UPBM-0001           1  2027         1          24

[44568 rows x 6 columns]

In [ ]:
#Proceso de validación de los datos para asegurar que el dataset cumple con los requisitos esperados.
from matriculas.validate import (
    validate_dataset,
    DataValidationError,
)

try:
    validate_dataset(df_periods)
    print("Dataset válido")
except DataValidationError as error:
    print(f"Dataset inválido: {error}")

Dataset válido